2024-11-14 12:09:50,548 INFO    StreamThr :55340 [internal.py:wandb_internal():85] W&B internal server running at pid: 55340, started at: 2024-11-14 12:09:50.547698
2024-11-14 12:09:50,550 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status
2024-11-14 12:09:50,559 INFO    WriterThread:55340 [datastore.py:open_for_write():87] open: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/run-22d3obyx.wandb
2024-11-14 12:09:50,560 DEBUG   SenderThread:55340 [sender.py:send():389] send: header
2024-11-14 12:09:50,573 DEBUG   SenderThread:55340 [sender.py:send():389] send: run
2024-11-14 12:09:50,988 INFO    SenderThread:55340 [dir_watcher.py:__init__():211] watching files in: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files
2024-11-14 12:09:50,989 INFO    SenderThread:55340 [sender.py:_start_run_threads():1157] run started: 22d3obyx with start time 1731582590.547393
2024-11-14 12:09:51,006 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: run_start
2024-11-14 12:09:51,014 DEBUG   HandlerThread:55340 [system_info.py:__init__():26] System info init
2024-11-14 12:09:51,014 DEBUG   HandlerThread:55340 [system_info.py:__init__():41] System info init done
2024-11-14 12:09:51,014 INFO    HandlerThread:55340 [system_monitor.py:start():194] Starting system monitor
2024-11-14 12:09:51,014 INFO    SystemMonitor:55340 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-11-14 12:09:51,014 INFO    HandlerThread:55340 [system_monitor.py:probe():214] Collecting system info
2024-11-14 12:09:51,015 INFO    SystemMonitor:55340 [interfaces.py:start():188] Started cpu monitoring
2024-11-14 12:09:51,018 INFO    SystemMonitor:55340 [interfaces.py:start():188] Started disk monitoring
2024-11-14 12:09:51,022 INFO    SystemMonitor:55340 [interfaces.py:start():188] Started gpuapple monitoring
2024-11-14 12:09:51,024 INFO    SystemMonitor:55340 [interfaces.py:start():188] Started memory monitoring
2024-11-14 12:09:51,025 INFO    SystemMonitor:55340 [interfaces.py:start():188] Started network monitoring
2024-11-14 12:09:51,147 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:09:51,244 ERROR   HandlerThread:55340 [gpu_apple.py:probe():176] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:09:51,244 DEBUG   HandlerThread:55340 [system_info.py:probe():152] Probing system
2024-11-14 12:09:51,248 DEBUG   HandlerThread:55340 [system_info.py:_probe_git():137] Probing git
2024-11-14 12:09:51,264 DEBUG   HandlerThread:55340 [system_info.py:_probe_git():145] Probing git done
2024-11-14 12:09:51,264 DEBUG   HandlerThread:55340 [system_info.py:probe():200] Probing system done
2024-11-14 12:09:51,264 DEBUG   HandlerThread:55340 [system_monitor.py:probe():223] {'os': 'macOS-13.4.1-arm64-arm-64bit', 'python': '3.11.1', 'heartbeatAt': '2024-11-14T11:09:51.244986', 'startedAt': '2024-11-14T11:09:50.535746', 'docker': None, 'cuda': None, 'args': ('--config-name', 'lgbm-conf'), 'state': 'running', 'program': '/Users/dan/Documents/src/COMP-STUDY/synced/lightgbm_model.py', 'codePathLocal': 'lightgbm_model.py', 'codePath': 'lightgbm_model.py', 'git': {'remote': 'git@github.com:Siigull/AL-Comparative-Study.git', 'commit': '7e7a49d7642bb2c5d4879014e26f7ca35fa0c5ae'}, 'email': None, 'root': '/Users/dan/Documents/src/COMP-STUDY/synced', 'host': 'Daniels-MacBook-Air-2.local', 'username': 'dan', 'executable': '/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 11.198070526123047}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-11-14 12:09:51,264 INFO    HandlerThread:55340 [system_monitor.py:probe():224] Finished collecting system info
2024-11-14 12:09:51,264 INFO    HandlerThread:55340 [system_monitor.py:probe():227] Publishing system info
2024-11-14 12:09:51,264 INFO    HandlerThread:55340 [system_monitor.py:probe():229] Finished publishing system info
2024-11-14 12:09:51,267 DEBUG   SenderThread:55340 [sender.py:send():389] send: files
2024-11-14 12:09:51,267 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file wandb-metadata.json with policy now
2024-11-14 12:09:51,447 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: python_packages
2024-11-14 12:09:51,447 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: python_packages
2024-11-14 12:09:51,448 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:09:51,448 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:09:51,449 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:09:51,698 DEBUG   SenderThread:55340 [sender.py:send():389] send: telemetry
2024-11-14 12:09:51,885 INFO    wandb-upload_0:55340 [upload_job.py:push():130] Uploaded file /var/folders/8f/6dw3knc955311yk7rhd5t4980000gn/T/tmph5bfcamowandb/und8ry9d-wandb-metadata.json
2024-11-14 12:09:51,994 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/requirements.txt
2024-11-14 12:09:51,995 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:09:51,995 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-metadata.json
2024-11-14 12:09:53,289 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:09:54,005 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:09:55,418 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:09:55,765 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:09:56,015 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:09:57,654 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:09:59,790 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:01,453 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:01,457 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:01,921 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:04,062 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:06,192 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:06,452 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:10:06,453 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:10:06,757 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:08,458 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:10,075 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:10,642 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:11,457 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:12,081 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:12,469 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:12,775 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:14,945 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:16,103 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:17,076 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:17,475 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:18,113 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:19,212 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:21,370 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:21,456 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:10:21,457 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:21,457 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:10:22,127 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:22,571 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:23,132 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/config.yaml
2024-11-14 12:10:23,510 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:24,137 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:25,728 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:27,885 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:27,946 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:28,156 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:30,178 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:31,462 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:32,398 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:33,496 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:34,618 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:36,462 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:10:36,463 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:10:36,839 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:38,669 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:39,062 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:41,274 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:41,467 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:43,488 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:44,510 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:45,700 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:47,910 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:49,525 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:50,121 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:51,028 DEBUG   SystemMonitor:55340 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-11-14 12:10:51,030 DEBUG   SenderThread:55340 [sender.py:send():389] send: telemetry
2024-11-14 12:10:51,030 DEBUG   SenderThread:55340 [sender.py:send():389] send: stats
2024-11-14 12:10:51,466 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:10:51,467 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:10:51,470 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:10:52,335 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:54,545 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:54,801 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:10:55,292 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/config.yaml
2024-11-14 12:10:56,299 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:10:56,824 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:10:59,045 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:00,524 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:01,260 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:01,475 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:03,474 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:05,528 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:05,682 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:06,470 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:11:06,471 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:11:07,893 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:10,105 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:10,677 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:11,478 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:12,332 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:14,550 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:16,531 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:16,769 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:18,981 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:21,041 DEBUG   SenderThread:55340 [sender.py:send():389] send: stats
2024-11-14 12:11:21,210 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:21,471 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:11:21,471 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:11:21,483 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:21,679 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:23,420 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:25,636 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:26,448 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:11:27,541 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:27,852 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:30,068 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:31,488 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:32,296 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:32,549 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:34,512 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:36,475 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:11:36,476 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:11:36,725 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:37,734 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:38,940 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:41,156 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:41,493 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:43,379 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:43,562 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:45,598 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:47,810 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:48,566 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:50,025 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:51,039 DEBUG   SenderThread:55340 [sender.py:send():389] send: stats
2024-11-14 12:11:51,480 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:11:51,481 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:11:51,497 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:11:52,242 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:53,828 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:11:54,452 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:56,666 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:58,598 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:11:58,916 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:11:59,600 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:01,183 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:01,500 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:12:03,437 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:05,599 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:05,692 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:06,489 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:12:06,494 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:12:07,949 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:10,243 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:10,797 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:11,506 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:12:12,449 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:14,731 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:16,581 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:16,965 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:19,239 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:21,049 DEBUG   SenderThread:55340 [sender.py:send():389] send: stats
2024-11-14 12:12:21,488 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: stop_status
2024-11-14 12:12:21,489 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: stop_status
2024-11-14 12:12:21,493 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:21,506 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:12:21,786 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:22,203 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: partial_history
2024-11-14 12:12:22,204 DEBUG   SenderThread:55340 [sender.py:send():389] send: history
2024-11-14 12:12:22,204 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: summary_record
2024-11-14 12:12:22,205 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file wandb-summary.json with policy end
2024-11-14 12:12:22,739 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-summary.json
2024-11-14 12:12:22,806 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: log_artifact
2024-11-14 12:12:22,806 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: log_artifact
2024-11-14 12:12:23,243 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: partial_history
2024-11-14 12:12:23,705 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:23,745 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/media/table/eval/report_1_97f7df5ea97baec26ad9.table.json
2024-11-14 12:12:23,745 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/media
2024-11-14 12:12:23,746 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/media/table
2024-11-14 12:12:23,746 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/media/table/eval
2024-11-14 12:12:24,179 INFO    wandb-upload_1:55340 [upload_job.py:push():130] Uploaded file /var/folders/8f/6dw3knc955311yk7rhd5t4980000gn/T/tmph5bfcamowandb/xq1mz0di-media/table/eval/report_1_97f7df5ea97baec26ad9.table.json
2024-11-14 12:12:24,898 INFO    wandb-upload_0:55340 [upload_job.py:push():88] Uploaded file /Users/dan/Library/Application Support/wandb/artifacts/staging/tmpkr9n4xyu
2024-11-14 12:12:25,691 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:25,777 INFO    SenderThread:55340 [sender.py:send_request_log_artifact():1494] logged artifact run-22d3obyx-evalreport - {'id': 'QXJ0aWZhY3Q6MTMzNDgyNjYxOA==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQ5NTgzMDgyNg==', 'latestArtifact': None}}
2024-11-14 12:12:25,778 DEBUG   SenderThread:55340 [sender.py:send():389] send: files
2024-11-14 12:12:25,778 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file media/table/eval/report_1_97f7df5ea97baec26ad9.table.json with policy now
2024-11-14 12:12:25,778 DEBUG   SenderThread:55340 [sender.py:send():389] send: history
2024-11-14 12:12:25,778 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: summary_record
2024-11-14 12:12:25,779 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file wandb-summary.json with policy end
2024-11-14 12:12:25,779 DEBUG   SenderThread:55340 [sender.py:send():389] send: exit
2024-11-14 12:12:25,779 INFO    SenderThread:55340 [sender.py:send_exit():577] handling exit code: 0
2024-11-14 12:12:25,779 INFO    SenderThread:55340 [sender.py:send_exit():579] handling runtime: 153
2024-11-14 12:12:25,780 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file wandb-summary.json with policy end
2024-11-14 12:12:25,780 INFO    SenderThread:55340 [sender.py:send_exit():585] send defer
2024-11-14 12:12:25,780 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:25,780 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,780 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 0
2024-11-14 12:12:25,780 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,780 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 0
2024-11-14 12:12:25,780 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 1
2024-11-14 12:12:25,780 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,780 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 1
2024-11-14 12:12:25,781 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,781 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 1
2024-11-14 12:12:25,781 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 2
2024-11-14 12:12:25,781 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,782 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 2
2024-11-14 12:12:25,782 INFO    HandlerThread:55340 [system_monitor.py:finish():203] Stopping system monitor
2024-11-14 12:12:25,782 DEBUG   SystemMonitor:55340 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-11-14 12:12:25,782 DEBUG   SystemMonitor:55340 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-11-14 12:12:25,783 INFO    HandlerThread:55340 [interfaces.py:finish():200] Joined cpu monitor
2024-11-14 12:12:25,783 INFO    HandlerThread:55340 [interfaces.py:finish():200] Joined disk monitor
2024-11-14 12:12:25,859 ERROR   gpuapple  :55340 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-11-14 12:12:25,859 INFO    HandlerThread:55340 [interfaces.py:finish():200] Joined gpuapple monitor
2024-11-14 12:12:25,859 INFO    HandlerThread:55340 [interfaces.py:finish():200] Joined memory monitor
2024-11-14 12:12:25,859 INFO    HandlerThread:55340 [interfaces.py:finish():200] Joined network monitor
2024-11-14 12:12:25,859 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,859 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 2
2024-11-14 12:12:25,859 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 3
2024-11-14 12:12:25,860 DEBUG   SenderThread:55340 [sender.py:send():389] send: stats
2024-11-14 12:12:25,860 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,860 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 3
2024-11-14 12:12:25,860 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,860 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 3
2024-11-14 12:12:25,860 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 4
2024-11-14 12:12:25,860 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,860 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 4
2024-11-14 12:12:25,860 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,860 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 4
2024-11-14 12:12:25,860 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 5
2024-11-14 12:12:25,860 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,860 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 5
2024-11-14 12:12:25,860 DEBUG   SenderThread:55340 [sender.py:send():389] send: summary
2024-11-14 12:12:25,860 INFO    SenderThread:55340 [sender.py:_save_file():1423] saving file wandb-summary.json with policy end
2024-11-14 12:12:25,861 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,861 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 5
2024-11-14 12:12:25,861 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 6
2024-11-14 12:12:25,861 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,861 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 6
2024-11-14 12:12:25,861 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,861 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 6
2024-11-14 12:12:25,861 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 7
2024-11-14 12:12:25,861 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: status_report
2024-11-14 12:12:25,861 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:25,861 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 7
2024-11-14 12:12:25,861 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:25,861 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 7
2024-11-14 12:12:26,262 INFO    wandb-upload_1:55340 [upload_job.py:push():130] Uploaded file /var/folders/8f/6dw3knc955311yk7rhd5t4980000gn/T/tmph5bfcamowandb/tdsqx4za-media/table/eval/report_1_97f7df5ea97baec26ad9.table.json
2024-11-14 12:12:26,694 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:26,763 INFO    Thread-12 :55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-summary.json
2024-11-14 12:12:28,239 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 8
2024-11-14 12:12:28,239 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:28,239 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:28,240 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 8
2024-11-14 12:12:28,240 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:28,240 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 8
2024-11-14 12:12:28,240 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 9
2024-11-14 12:12:28,241 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:28,241 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 9
2024-11-14 12:12:28,241 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:28,241 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 9
2024-11-14 12:12:28,241 INFO    SenderThread:55340 [dir_watcher.py:finish():358] shutting down directory watcher
2024-11-14 12:12:28,703 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:28,770 INFO    SenderThread:55340 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:12:28,771 INFO    SenderThread:55340 [dir_watcher.py:finish():388] scan: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files
2024-11-14 12:12:28,771 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/requirements.txt requirements.txt
2024-11-14 12:12:28,771 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log output.log
2024-11-14 12:12:28,775 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/config.yaml config.yaml
2024-11-14 12:12:28,777 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-summary.json wandb-summary.json
2024-11-14 12:12:28,780 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-metadata.json wandb-metadata.json
2024-11-14 12:12:28,783 INFO    SenderThread:55340 [dir_watcher.py:finish():402] scan save: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/media/table/eval/report_1_97f7df5ea97baec26ad9.table.json media/table/eval/report_1_97f7df5ea97baec26ad9.table.json
2024-11-14 12:12:28,783 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 10
2024-11-14 12:12:28,783 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:28,784 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:28,784 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 10
2024-11-14 12:12:28,784 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:28,784 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 10
2024-11-14 12:12:28,784 INFO    SenderThread:55340 [file_pusher.py:finish():169] shutting down file pusher
2024-11-14 12:12:29,173 INFO    wandb-upload_0:55340 [upload_job.py:push():130] Uploaded file /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/requirements.txt
2024-11-14 12:12:29,189 INFO    wandb-upload_1:55340 [upload_job.py:push():130] Uploaded file /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/output.log
2024-11-14 12:12:29,249 INFO    wandb-upload_3:55340 [upload_job.py:push():130] Uploaded file /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/wandb-summary.json
2024-11-14 12:12:29,251 INFO    wandb-upload_2:55340 [upload_job.py:push():130] Uploaded file /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/files/config.yaml
2024-11-14 12:12:29,457 INFO    Thread-11 (_thread_body):55340 [sender.py:transition_state():605] send defer: 11
2024-11-14 12:12:29,458 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:29,458 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 11
2024-11-14 12:12:29,459 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:29,459 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 11
2024-11-14 12:12:29,459 INFO    SenderThread:55340 [file_pusher.py:join():175] waiting for file pusher
2024-11-14 12:12:29,461 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 12
2024-11-14 12:12:29,462 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:29,462 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 12
2024-11-14 12:12:29,462 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:29,462 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 12
2024-11-14 12:12:29,462 INFO    SenderThread:55340 [file_stream.py:finish():601] file stream finish called
2024-11-14 12:12:29,710 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:30,026 INFO    SenderThread:55340 [file_stream.py:finish():605] file stream finish is done
2024-11-14 12:12:30,027 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 13
2024-11-14 12:12:30,027 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:30,027 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:30,028 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 13
2024-11-14 12:12:30,028 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:30,028 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 13
2024-11-14 12:12:30,029 INFO    SenderThread:55340 [sender.py:transition_state():605] send defer: 14
2024-11-14 12:12:30,029 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: defer
2024-11-14 12:12:30,029 DEBUG   SenderThread:55340 [sender.py:send():389] send: final
2024-11-14 12:12:30,029 INFO    HandlerThread:55340 [handler.py:handle_request_defer():184] handle defer: 14
2024-11-14 12:12:30,029 DEBUG   SenderThread:55340 [sender.py:send():389] send: footer
2024-11-14 12:12:30,030 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: defer
2024-11-14 12:12:30,030 INFO    SenderThread:55340 [sender.py:send_request_defer():601] handle sender defer: 14
2024-11-14 12:12:30,030 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:30,031 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:30,031 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: poll_exit
2024-11-14 12:12:30,031 DEBUG   SenderThread:55340 [sender.py:send_request():416] send_request: poll_exit
2024-11-14 12:12:30,032 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: get_summary
2024-11-14 12:12:30,032 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: sampled_history
2024-11-14 12:12:30,033 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: internal_messages
2024-11-14 12:12:30,033 INFO    MainThread:55340 [wandb_run.py:_footer_history_summary_info():4049] rendering history
2024-11-14 12:12:30,033 INFO    MainThread:55340 [wandb_run.py:_footer_history_summary_info():4081] rendering summary
2024-11-14 12:12:30,033 INFO    MainThread:55340 [wandb_run.py:_footer_sync_info():4008] logging synced files
2024-11-14 12:12:30,034 DEBUG   HandlerThread:55340 [handler.py:handle_request():158] handle_request: shutdown
2024-11-14 12:12:30,034 INFO    HandlerThread:55340 [handler.py:finish():874] shutting down handler
2024-11-14 12:12:31,036 INFO    SenderThread:55340 [sender.py:finish():1589] shutting down sender
2024-11-14 12:12:31,036 INFO    SenderThread:55340 [file_pusher.py:finish():169] shutting down file pusher
2024-11-14 12:12:31,036 INFO    SenderThread:55340 [file_pusher.py:join():175] waiting for file pusher
2024-11-14 12:12:31,037 INFO    WriterThread:55340 [datastore.py:close():296] close: /Users/dan/Documents/src/COMP-STUDY/synced/wandb/run-20241114_120950-22d3obyx/run-22d3obyx.wandb
